### ISSUE TITLE
No layout in this folder

### ISSUE THREAD

**Issue by PRAVEJOE** [QArtur99/Compose-ShoppingList#3]

**Comment by QArtur99** [comment]
UI is built from kt files via Jetpack Compose.

**Comment by PRAVEJOE** [comment]
![image](https://user-images.githubusercontent.com/53892530/115958623-ca386a80-a525-11eb-8a49-7404cbf30f0d.png)
This error pops up
How can this be fixed?

**Comment by QArtur99** [comment]
Gradle hasn't been updated to version 7.0-RC. I have pushed a new commit that fixes it so pull changes or update it manually.
btw: It requires JDK 11.

**Comment by QArtur99** [comment]
It requires JDK 11 as well.
